<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>goshell</string>
	</array>
	<key>name</key>
	<string>GoTPL: Shell</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>source.shell</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.gotemplate</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.goshell</string>
	<key>uuid</key>
    <string>3cc4c606-32f6-25d9-4a40-9a566ef97a04</string>
</dict>
</plist>
